### ISSUE TITLE
Re-enable testing nightly NEURON wheels against the latest Fedora release

### ISSUE THREAD

**Issue by olupton** [neuronsimulator/nrn-build-ci#31]
NEURON wheels are not currently built against Python 3.10, so the CI fails on `fedora:latest` even if the actual build + test steps pass: https://github.com/neuronsimulator/nrn-build-ci/runs/4163851845

In https://github.com/neuronsimulator/nrn-build-ci/pull/30, testing the nightly wheels on `fedora:latest` is disabled. We should re-enable that combination when possible.

**Comment by olupton** [comment]
@alexsavulescu can this be addressed now?

**Comment by alexsavulescu** [comment]
Indeed. Seems like we don't have any guards for `main` as I have inadvertently committed to it from GH web.

**Comment by alexsavulescu** [comment]
Plus I don't have the rights to set up any protection.

**Comment by olupton** [comment]
Thanks @alexsavulescu ! I added some protection for `main` just now.
